title: FarmBot Documentation Hub
description: 100% open-source assembly instructions, CAD models, software, and more
baseurl: /
exclude:
  - docs
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
