title: FarmBot Documentation Hub
url: https://docs.farm.bot
description: 100% open-source assembly instructions, CAD models, software, and more
logo: /assets/images/farmbot-logo.png
baseurl: /
exclude:
  - docs
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
